name: test-goci
on: [push]
jobs:
  check-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Tests"
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup golang
        uses: actions/setup-go@v3
      - name: Run unit tests
        run: go test goci
      